spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=url-shortener
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379