version: '3'

services:
  zookeeper:
    image: zookeeper:3.5.6
    hostname: zookeeper-srv
    ports:
      - "2181:2181"
    volumes:
      - ./zk-single-kafka-single/zoo1/data :/data
      - ./zk-single-kafka-single/zoo1/datalog :/datalog
  kafka:
    image: confluentinc/cp-kafka:5.4.0
    hostname: kafka-cluster
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka-cluster:9092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-serv:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 11
    volumes:
      - ./zk-single-kafka-single/kafka/data :/var/lib/kafka/data
    depends_on:
      - zookeeper